version: '3.8'
services:
  app:
    build:
      context: ./  # Continuação da sua configuração para o serviço app
    container_name: cakephp_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1tBZtkzDGuDPQG8
      POSTGRES_DATABASE: postgres
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}"
    networks:
      - cakephp_network

  db:
    image: postgres:13
    container_name: cakephp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1tBZtkzDGuDPQG8
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cakephp_network

  nginx:
    image: nginx:latest  # Imagem do Nginx
    container_name: cakephp_nginx
    ports:
      - "8080:80"  # Mapeia a porta 80 do Nginx para a porta 8080 do host
    volumes:
      - ./:/var/www/html  # Mapeia os arquivos do projeto
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mapeia o arquivo de configuração do Nginx
    depends_on:
      - app  # Garante que o app (PHP-FPM) esteja disponível
    networks:
      - cakephp_network

volumes:
  db_data:
  
networks:
  default:
    external:
      name: bridge
