version: '3.8'

services:
  web:
    build: .
    container_name: cakephp_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/webroot
    networks:
      - cakephp_network

networks:
  cakephp_network:
    driver: bridge
