version: '3.8'

services:
  app:
    build:
      context: .  # O caminho do diretório onde o Dockerfile está localizado
    container_name: cakephp_app
    ports:
      - "8080:80"  # Mapeia a porta 80 do Apache para a 8080 no host
    volumes:
      - ./:/var/www/html  # Mapeia os arquivos do projeto para o contêiner
    depends_on:
      - db  # A aplicação depende do banco de dados
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1tBZtkzDGuDPQG8
      POSTGRES_DB: postgres
    networks:
      - cakephp_network

  db:
    image: postgres:13
    container_name: cakephp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cakephp_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cakephp_network

volumes:
  db_data:  # Volumes para persistir os dados do banco

networks:
  cakephp_network:
    driver: bridge
