version: '3'

services:
  cakephp:
    build: .
    ports:
      - "80:80"
    environment:
      - RUN_MIGRATIONS=true  # Ativa a execução de migrações
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
