version: '3.8'

services:
  app:
    image: jorgegonzalezcakedc/cakephp-runner
    container_name: cakephp_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1tBZtkzDGuDPQG8
      POSTGRES_DATABASE: postgres
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}"
    networks:
      - cakephp_network

  db:
    image: postgres:13
    container_name: cakephp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K1tBZtkzDGuDPQG8
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cakephp_network

volumes:
  db_data:

networks:
  default:
    external:
      name: bridge
